# Use an official Python runtime as a parent image
FROM python:3.11.8-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt first to leverage Docker cache
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Define environment variables
ENV MODULE_NAME="run_api"
ENV VARIABLE_NAME="app"
ENV PORT="8000"

# Expose port 8000
EXPOSE 8000

# Add a non-root user
RUN useradd -m fastapiuser
USER fastapiuser

# Healthcheck to ensure the application is running
HEALTHCHECK CMD curl --fail http://localhost:8000/health || exit 1

# Run FastAPI server when the container launches
CMD ["uvicorn", "run_api:app", "--host", "0.0.0.0", "--port", "8000"]
